# Generated by Django 4.1.3 on 2023-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TUTOR', 'Tutor'), ('STUDENT', 'Student')], max_length=50),
        ),
    ]
