---
site_name: LittleEye Korrekturmanagementsystem
site_description: Wie bedient man das Programm? 
site_author: Bernd, Tom, Asiye 
site_url: 
nav:
  - Introduction: index.md
  - Benutzerhandbuch:
      - Einleitung:
          - einleitung: content/einleitung.md
      - Authentifizierung:
          - anmeldung: content/anmeldung.md
      - Studentensicht:
          - das Studenten-Dashboard: content/dashboard-student.md
          - Funktionsübersicht: content/studenten-funktionen.md
      - Tutorensicht:
          - das Tutoren-Dashboard: content/dashboard-tutor.md
          - Funktionsübersicht: content/tutoren-funktionen.md
      - Allgemeines:
          - FAQ: content/faq.md
          - Troubleshooting: content/troubleshooting.md
  - Contact: content/contact.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/littleeye-logo.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

extra:
  social:
    - icon: fontawesome/brands/github-alt

repo_name: teleponi/littleeye
repo_url: https://github.com/teleponi/littleeye
