# Generated by Django 4.2.2 on 2023-06-29 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('lecturer', models.ManyToManyField(limit_choices_to={'role': 'TUTOR'}, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
