# Generated by Django 4.2.2 on 2023-07-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tutor_alter_course_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
    ]
