# Generated by Django 4.1.3 on 2023-07-30 01:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_remove_course_description_course_shortcut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('icon', models.CharField(blank=True, max_length=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=19, null=True)),
                ('name', models.CharField(max_length=99, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('location', models.CharField(blank=True, help_text='Wo ist der Fehler aufgetreten? Zeile, Minute, Seite, ect.', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'normal'), (2, 'dringend'), (3, 'sofort')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'neu eingestellt'), (1, 'in Bearbeitung'), (2, 'erledigt'), (3, 'geschlossen')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='courses.course')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='issues.mediatype')),
                ('tags', models.ManyToManyField(blank=True, related_name='tickets', to='issues.tag')),
            ],
            options={
                'ordering': ['-severity', 'status'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'Ticket wurde erstellt'), (2, 'Status wurde geändert'), (3, 'Kommentar wurde hinzugefügt'), (4, 'Ticket wurde geschlossen')])),
                ('status', models.IntegerField(choices=[(0, 'neu eingestellt'), (1, 'in Bearbeitung'), (2, 'erledigt'), (3, 'geschlossen')])),
                ('severity', models.IntegerField(choices=[(1, 'normal'), (2, 'dringend'), (3, 'sofort')])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='issues.ticket')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='der Titel muss mindestens drei Zeichen lang sein!')])),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('author', 'name', 'created_at'), name='unique_author'),
        ),
    ]
