# Generated by Django 4.2.2 on 2023-06-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('issues', '0002_issue_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='courses.course'),
            preserve_default=False,
        ),
    ]
