# Generated by Django 4.1.3 on 2023-08-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_tickethistory_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediatype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
