# Generated by Django 4.2.2 on 2023-07-01 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0003_alter_issue_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='iusses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
