# Generated by Django 4.1.3 on 2023-08-13 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.CharField(blank=True, help_text='Wo ist der Fehler aufgetreten? Zeile, Minute, Seite, ect.', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
