# Generated by Django 4.2.2 on 2023-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'in Bearbeitung'), (2, 'geschlossen'), (3, 'wiedergeöffnet')], default=1),
            preserve_default=False,
        ),
    ]
