# Generated by Django 4.2.2 on 2023-07-01 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0005_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tissues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'in Bearbeitung'), (2, 'geschlossen'), (3, 'wiedergeöffnet')], default=1),
        ),
    ]
