# Generated by Django 4.2.2 on 2023-07-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_tutor_alter_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='tutor',
        ),
    ]
