# Generated by Django 4.2.2 on 2023-07-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_remove_issue_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(default='hse'),
            preserve_default=False,
        ),
    ]
