# Generated by Django 4.2.2 on 2023-07-02 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_issue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(blank=True, help_text='Wo ist der Fehler aufgetreten? Zeile, Minute, Seite, ect.', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
