# Generated by Django 4.2.2 on 2023-07-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0011_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediatype",
            name="icon",
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="icon",
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
