# Generated by Django 4.2.2 on 2023-07-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0012_alter_mediatype_icon_alter_tag_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Ticket wurde erstellt"),
                            (2, "Status wurde geändert"),
                            (3, "Kommentar wurde hinzugefügt"),
                            (4, "Ticket wurde geschlossen"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "in Bearbeitung"),
                            (2, "geschlossen"),
                            (3, "wiedergeöffnet"),
                        ]
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "unbedeutend"),
                            (2, "normal"),
                            (3, "dringend"),
                            (4, "sofort"),
                        ]
                    ),
                ),
                (
                    "issue",
                    models.ManyToManyField(related_name="history", to="issues.issue"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
