# Generated by Django 4.2.2 on 2023-07-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0013_issuehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuehistory",
            name="issue",
        ),
        migrations.AddField(
            model_name="issuehistory",
            name="issue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="issues.issue",
            ),
            preserve_default=False,
        ),
    ]
