# Generated by Django 4.2.2 on 2023-07-13 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0014_remove_issuehistory_issue_issuehistory_issue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="is_active",
        ),
    ]
