# Generated by Django 4.1.3 on 2023-07-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_remove_issue_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.IntegerField(choices=[(2, 'normal'), (3, 'dringend'), (4, 'sofort')]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'neu eingestellt'), (1, 'in Bearbeitung'), (2, 'erledigt'), (3, 'geschlossen')], default=1),
        ),
        migrations.AlterField(
            model_name='issuehistory',
            name='severity',
            field=models.IntegerField(choices=[(2, 'normal'), (3, 'dringend'), (4, 'sofort')]),
        ),
        migrations.AlterField(
            model_name='issuehistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'neu eingestellt'), (1, 'in Bearbeitung'), (2, 'erledigt'), (3, 'geschlossen')]),
        ),
    ]
