# Generated by Django 4.1.3 on 2023-03-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MODERATOR", "Moderator"),
                    ("PREMIUM", "Premium User"),
                ],
                default="ADMIN",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
