services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 project.asgi -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - static_volume_little:/home/app/web/staticfiles
    ports:
      - 8001:8000
    env_file:
      - ././app/.env.prod
    depends_on:
      - dbi
  dbi:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data_little:/var/lib/postgresql/data/
    env_file:
      - ././app/.env.db
volumes:
  postgres_data_little:
  static_volume_little:

networks:
  default:
    external: true
    name: proxymanager_default
